#!/usr/bin/env bash
# NL Devices Setup - Linux Optimization Script
# Applies low-latency and network optimizations

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(dirname "$SCRIPT_DIR")/../lib"

# Source common functions
# shellcheck source=../../lib/common.sh
source "$LIB_DIR/common.sh"

# Configuration
MODULES_DIR="$SCRIPT_DIR/modules"
SYSCTL_CONF="/etc/sysctl.d/99-nldevicessetup.conf"

show_help() {
    cat << EOF
NL Devices Setup - Linux Optimization

Usage: $(basename "$0") [OPTIONS]

Options:
    --help, -h          Show this help message
    --dry-run           Show what would be done without making changes
    --modules, -m MOD   Comma-separated list of modules (default: all)
    --list-modules      List available modules
    --rollback          Rollback to pre-optimization state

Available Modules:
    network     Network stack optimizations (TCP/UDP buffers, congestion)
    latency     Low-latency kernel parameters
    filesystem  Filesystem tuning (noatime, etc)
    realtime    Realtime scheduling setup
    all         Apply all modules

Examples:
    sudo $(basename "$0")                    # Apply all optimizations
    sudo $(basename "$0") -m network,latency # Apply specific modules
    sudo $(basename "$0") --dry-run          # Preview changes
EOF
}

list_modules() {
    log_info "Available modules:"
    echo ""
    for module in "$MODULES_DIR"/*.sh; do
        if [[ -f "$module" ]]; then
            local name
            name=$(basename "$module" .sh)
            local desc
            desc=$(grep -m1 '^# Description:' "$module" | cut -d: -f2- | xargs)
            printf "  %-15s %s\n" "$name" "${desc:-No description}"
        fi
    done
}

apply_module() {
    local module_name="$1"
    local module_file="$MODULES_DIR/${module_name}.sh"

    if [[ ! -f "$module_file" ]]; then
        log_error "Module not found: $module_name"
        return 1
    fi

    log_info "Applying module: $module_name"
    # shellcheck source=/dev/null
    source "$module_file"

    if declare -f "apply_${module_name}" &>/dev/null; then
        "apply_${module_name}"
    else
        log_error "Module $module_name does not define apply_${module_name}()"
        return 1
    fi
}

apply_core_optimizations() {
    log_info "Applying core optimizations..."

    # Backup existing config
    backup_file "$SYSCTL_CONF"

    # Create config header
    run_cmd tee "$SYSCTL_CONF" > /dev/null << 'EOF'
# NL Devices Setup - Low Latency Optimizations
# Generated by nldevicessetup
# https://github.com/zbynekdrlik/nldevicessetup

EOF

    # Network optimizations
    log_info "Configuring network stack..."

    # Increase network buffer sizes
    set_sysctl "net.core.rmem_max" "26214400"
    persist_sysctl "net.core.rmem_max" "26214400" "$SYSCTL_CONF"

    set_sysctl "net.core.wmem_max" "26214400"
    persist_sysctl "net.core.wmem_max" "26214400" "$SYSCTL_CONF"

    set_sysctl "net.core.rmem_default" "1048576"
    persist_sysctl "net.core.rmem_default" "1048576" "$SYSCTL_CONF"

    set_sysctl "net.core.wmem_default" "1048576"
    persist_sysctl "net.core.wmem_default" "1048576" "$SYSCTL_CONF"

    # TCP optimizations
    set_sysctl "net.ipv4.tcp_rmem" "4096 1048576 26214400"
    persist_sysctl "net.ipv4.tcp_rmem" "4096 1048576 26214400" "$SYSCTL_CONF"

    set_sysctl "net.ipv4.tcp_wmem" "4096 1048576 26214400"
    persist_sysctl "net.ipv4.tcp_wmem" "4096 1048576 26214400" "$SYSCTL_CONF"

    # Disable TCP slow start after idle
    set_sysctl "net.ipv4.tcp_slow_start_after_idle" "0"
    persist_sysctl "net.ipv4.tcp_slow_start_after_idle" "0" "$SYSCTL_CONF"

    # Use BBR congestion control if available
    if [[ -f /proc/sys/net/ipv4/tcp_available_congestion_control ]]; then
        if grep -q bbr /proc/sys/net/ipv4/tcp_available_congestion_control; then
            set_sysctl "net.ipv4.tcp_congestion_control" "bbr"
            persist_sysctl "net.ipv4.tcp_congestion_control" "bbr" "$SYSCTL_CONF"
        fi
    fi

    # Low latency optimizations
    log_info "Configuring low-latency parameters..."

    # Reduce swappiness for audio workloads
    set_sysctl "vm.swappiness" "10"
    persist_sysctl "vm.swappiness" "10" "$SYSCTL_CONF"

    # Improve kernel responsiveness
    set_sysctl "kernel.sched_min_granularity_ns" "1000000"
    persist_sysctl "kernel.sched_min_granularity_ns" "1000000" "$SYSCTL_CONF"

    set_sysctl "kernel.sched_wakeup_granularity_ns" "500000"
    persist_sysctl "kernel.sched_wakeup_granularity_ns" "500000" "$SYSCTL_CONF"

    # Apply sysctl changes
    run_cmd sysctl -p "$SYSCTL_CONF"

    log_success "Core optimizations applied"
}

show_summary() {
    echo ""
    log_success "=== Optimization Complete ==="
    echo ""
    log_info "Applied settings are now active and will persist across reboots."
    log_info "Configuration saved to: $SYSCTL_CONF"
    echo ""
    log_info "To verify settings:"
    log_info "  sysctl -a | grep -E '(rmem|wmem|swappiness|tcp_congestion)'"
    echo ""
}

main() {
    local modules="all"
    local dry_run="false"

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h)
                show_help
                exit 0
                ;;
            --dry-run)
                dry_run="true"
                DRY_RUN="true"
                shift
                ;;
            --modules|-m)
                modules="$2"
                shift 2
                ;;
            --list-modules)
                list_modules
                exit 0
                ;;
            --rollback)
                log_error "Rollback not yet implemented"
                exit 1
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # Require root
    require_root

    log_info "NL Devices Setup - Linux Optimizer v${NLDEVICESSETUP_VERSION}"
    log_info "Mode: $([ "$dry_run" = "true" ] && echo "DRY-RUN" || echo "LIVE")"
    echo ""

    # Apply core optimizations
    apply_core_optimizations

    # Apply additional modules if requested
    if [[ "$modules" != "all" ]]; then
        IFS=',' read -ra module_list <<< "$modules"
        for module in "${module_list[@]}"; do
            apply_module "$module"
        done
    fi

    if [[ "$dry_run" != "true" ]]; then
        show_summary
    fi
}

main "$@"
