apiVersion: nldevicessetup/v1
kind: Recipe
metadata:
  name: ssh-setup
  description: Configure SSH server for remote access
  tags:
    - ssh
    - remote-access
    - security
  version: "1.0.0"

spec:
  platforms:
    - windows
    - linux

  actions:
    - name: Install OpenSSH Server
      description: Install and enable SSH server for remote management
      windows:
        module: command
        params:
          commands:
            - Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            - Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
            - Set-Service -Name sshd -StartupType Automatic
            - Start-Service sshd
      linux:
        module: apt
        params:
          packages:
            - openssh-server
          post_install:
            - systemctl enable ssh
            - systemctl start ssh
      verify:
        windows: Get-Service sshd | Where-Object { $_.Status -eq 'Running' }
        linux: systemctl is-active ssh

    - name: Configure SSH Firewall
      description: Allow SSH through firewall
      windows:
        module: command
        params:
          command: |
            $rule = Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue
            if (-not $rule) {
              New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
            }
      linux:
        module: command
        params:
          command: |
            if command -v ufw &>/dev/null; then
              ufw allow ssh
            fi

    - name: Create SSH User
      description: Create dedicated SSH user for remote access
      when: create_ssh_user == true
      windows:
        module: command
        params:
          command: |
            $username = '{{ ssh_user }}'
            $existingUser = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
            if (-not $existingUser) {
              $password = ConvertTo-SecureString '{{ ssh_password }}' -AsPlainText -Force
              New-LocalUser -Name $username -Password $password -PasswordNeverExpires -UserMayNotChangePassword
              Add-LocalGroupMember -Group 'Administrators' -Member $username
            }
      linux:
        module: command
        params:
          command: |
            username='{{ ssh_user }}'
            if ! id "$username" &>/dev/null; then
              useradd -m -s /bin/bash "$username"
              usermod -aG sudo "$username"
            fi
